netdiff: netdiff.cpp
	g++ -o netdiff netdiff.cpp ../lib/ailib.a ../lib/imlib.a
	
neteval: neteval.cpp
	g++ -o neteval neteval.cpp ../lib/ailib.a ../lib/imlib.a

gensave: gensave.cpp
	g++ -o gensave gensave.cpp ../lib/ailib.a ../lib/imlib.a

clean:
	rm *.exe